"""add_message_id_to_feedback

Revision ID: 6fda32c41ee9
Revises: 0004
Create Date: 2026-05-23 21:01:38.365047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fda32c41ee9'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedbacks', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'message_id')
    # ### end Alembic commands ###
